.\" drol man page
.\" Contact bradley.sadowsky@gmail.com to correct errors or typos
.TH man 1 "23 May 2017" "3.0.0" "drol man page"
.SH NAME
drol \- drol is a simple esolang compiler (for DROL) written by Bradley Sadowsky. It is under the MIT
License, and is currently on version 3.0
.SH SYNOPSIS
drol.py
.RB [-c]
infile
.SH DESCRIPTION
.B DROL
is a simple compiler written in Python that translates DROL (Double Register Optimization Language) 
source code into C. DROL implements a system known as a register system (similar to the accumulators 
in deadfish) which consists of two registers (integers of the `int' C type) that can be manipulated
with different commands.
.SH DOCS
For more information and a list of commands, see the docs (DOCS.txt) which is present in the repository
 that DROL is present in.
.SH BUGS
There are known bugs currently.
.SH AUTHOR
Written by Bradley Sadowsky <bradley.sadowsky@gmail.com>
